application: madiolahb
version: alpha
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?_darcs/.*

inbound_services:
- mail
- xmpp_message

handlers:
# Main redirect to documentation
- url: /
  script: home.py

# Stats pages
- url: /(game|char)/.*
  script: stats.py

# Channel pages
- url: /channel.*
  script: channel.py
  login: required

# Email
- url: /_ah/mail/.*
  script: mail.py
  login: admin

# XMPP
- url: /_ah/xmpp/message/chat/
  script: xmpp.py
  login: admin

# GWave
- url: /_wave/.*
  script: wave.py

# Documentation
- url: /docs
  static_dir: docs

# Static Files
- url: /static
  static_dir: static

- url: /favicon\.ico|/static/favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/vnd.microsoft.icon
